//AM-RentalManagementV1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: src/api/specification/api_specification_am_rental_management.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RentCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartDate  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Vin        *Vin                   `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	CustomerId string                 `protobuf:"bytes,4,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *RentCarRequest) Reset() {
	*x = RentCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentCarRequest) ProtoMessage() {}

func (x *RentCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentCarRequest.ProtoReflect.Descriptor instead.
func (*RentCarRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{0}
}

func (x *RentCarRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *RentCarRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *RentCarRequest) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *RentCarRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type RentCarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rental *Rental      `protobuf:"bytes,1,opt,name=rental,proto3" json:"rental,omitempty"`
	Error  *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RentCarResponse) Reset() {
	*x = RentCarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentCarResponse) ProtoMessage() {}

func (x *RentCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentCarResponse.ProtoReflect.Descriptor instead.
func (*RentCarResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{1}
}

func (x *RentCarResponse) GetRental() *Rental {
	if x != nil {
		return x.Rental
	}
	return nil
}

func (x *RentCarResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListRentalsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *ListRentalsRequest) Reset() {
	*x = ListRentalsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRentalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRentalsRequest) ProtoMessage() {}

func (x *ListRentalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRentalsRequest.ProtoReflect.Descriptor instead.
func (*ListRentalsRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{2}
}

func (x *ListRentalsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type ListRentalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rentals []*Rental    `protobuf:"bytes,1,rep,name=rentals,proto3" json:"rentals,omitempty"`
	Error   *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListRentalsResponse) Reset() {
	*x = ListRentalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRentalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRentalsResponse) ProtoMessage() {}

func (x *ListRentalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRentalsResponse.ProtoReflect.Descriptor instead.
func (*ListRentalsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{3}
}

func (x *ListRentalsResponse) GetRentals() []*Rental {
	if x != nil {
		return x.Rentals
	}
	return nil
}

func (x *ListRentalsResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type CancelRentalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RentalId string `protobuf:"bytes,1,opt,name=rentalId,proto3" json:"rentalId,omitempty"`
}

func (x *CancelRentalRequest) Reset() {
	*x = CancelRentalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRentalRequest) ProtoMessage() {}

func (x *CancelRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRentalRequest.ProtoReflect.Descriptor instead.
func (*CancelRentalRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRentalRequest) GetRentalId() string {
	if x != nil {
		return x.RentalId
	}
	return ""
}

type CancelRentalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool         `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CancelRentalResponse) Reset() {
	*x = CancelRentalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRentalResponse) ProtoMessage() {}

func (x *CancelRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRentalResponse.ProtoReflect.Descriptor instead.
func (*CancelRentalResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRentalResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CancelRentalResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListAvailableCarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *ListAvailableCarsRequest) Reset() {
	*x = ListAvailableCarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAvailableCarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableCarsRequest) ProtoMessage() {}

func (x *ListAvailableCarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableCarsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableCarsRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{6}
}

func (x *ListAvailableCarsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListAvailableCarsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ListAvailableCarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars  []*Car       `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Error *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListAvailableCarsResponse) Reset() {
	*x = ListAvailableCarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAvailableCarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableCarsResponse) ProtoMessage() {}

func (x *ListAvailableCarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableCarsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableCarsResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{7}
}

func (x *ListAvailableCarsResponse) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *ListAvailableCarsResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RegisterCustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RegisterCustomerRequest) Reset() {
	*x = RegisterCustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCustomerRequest) ProtoMessage() {}

func (x *RegisterCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCustomerRequest.ProtoReflect.Descriptor instead.
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterCustomerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer *Customer    `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Error    *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RegisterCustomerResponse) Reset() {
	*x = RegisterCustomerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCustomerResponse) ProtoMessage() {}

func (x *RegisterCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCustomerResponse.ProtoReflect.Descriptor instead.
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *RegisterCustomerResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeregisterCustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *DeregisterCustomerRequest) Reset() {
	*x = DeregisterCustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeregisterCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterCustomerRequest) ProtoMessage() {}

func (x *DeregisterCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterCustomerRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{10}
}

func (x *DeregisterCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeregisterCustomerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *ErrorDetail `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeregisterCustomerResponse) Reset() {
	*x = DeregisterCustomerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeregisterCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterCustomerResponse) ProtoMessage() {}

func (x *DeregisterCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterCustomerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterCustomerResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterCustomerResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{12}
}

func (x *Customer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Rental struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RentalId   string                 `protobuf:"bytes,1,opt,name=rentalId,proto3" json:"rentalId,omitempty"`
	StartDate  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Vin        *Vin                   `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
	CustomerId string                 `protobuf:"bytes,5,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *Rental) Reset() {
	*x = Rental{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rental) ProtoMessage() {}

func (x *Rental) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rental.ProtoReflect.Descriptor instead.
func (*Rental) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{13}
}

func (x *Rental) GetRentalId() string {
	if x != nil {
		return x.RentalId
	}
	return ""
}

func (x *Rental) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Rental) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Rental) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Rental) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin         *Vin   `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Brand       string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model       string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	PricePerDay int32  `protobuf:"varint,4,opt,name=pricePerDay,proto3" json:"pricePerDay,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{14}
}

func (x *Car) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetPricePerDay() int32 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

type Vin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *Vin) Reset() {
	*x = Vin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vin) ProtoMessage() {}

func (x *Vin) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vin.ProtoReflect.Descriptor instead.
func (*Vin) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{15}
}

func (x *Vin) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type ErrorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP(), []int{16}
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_src_api_specification_api_specification_am_rental_management_proto protoreflect.FileDescriptor

var file_src_api_specification_api_specification_am_rental_management_proto_rawDesc = []byte{
	0x0a, 0x42, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x76, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03,
	0x76, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x0f, 0x52, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x52, 0x06, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x34, 0x0a,
	0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x07, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x12, 0x33,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8a, 0x01, 0x0a, 0x18,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x7b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x04, 0x63, 0x61, 0x72, 0x73,
	0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52,
	0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b,
	0x0a, 0x19, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x1a, 0x44,
	0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e,
	0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xdd,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x34, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7c,
	0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x22, 0x17, 0x0a, 0x03,
	0x56, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x76, 0x69, 0x6e, 0x22, 0x41, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x8a, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x73, 0x12, 0x2a, 0x2e, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xa2, 0x02, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x07, 0x52, 0x65, 0x6e,
	0x74, 0x43, 0x61, 0x72, 0x12, 0x20, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x43, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x12, 0x24, 0x2e, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0c, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x2e, 0x72, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xfc, 0x01, 0x0a, 0x1a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x10, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x29, 0x2e,
	0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x12, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x72,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x72, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_api_specification_api_specification_am_rental_management_proto_rawDescOnce sync.Once
	file_src_api_specification_api_specification_am_rental_management_proto_rawDescData = file_src_api_specification_api_specification_am_rental_management_proto_rawDesc
)

func file_src_api_specification_api_specification_am_rental_management_proto_rawDescGZIP() []byte {
	file_src_api_specification_api_specification_am_rental_management_proto_rawDescOnce.Do(func() {
		file_src_api_specification_api_specification_am_rental_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_api_specification_api_specification_am_rental_management_proto_rawDescData)
	})
	return file_src_api_specification_api_specification_am_rental_management_proto_rawDescData
}

var file_src_api_specification_api_specification_am_rental_management_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_src_api_specification_api_specification_am_rental_management_proto_goTypes = []interface{}{
	(*RentCarRequest)(nil),             // 0: rentalmanagement.RentCarRequest
	(*RentCarResponse)(nil),            // 1: rentalmanagement.RentCarResponse
	(*ListRentalsRequest)(nil),         // 2: rentalmanagement.ListRentalsRequest
	(*ListRentalsResponse)(nil),        // 3: rentalmanagement.ListRentalsResponse
	(*CancelRentalRequest)(nil),        // 4: rentalmanagement.CancelRentalRequest
	(*CancelRentalResponse)(nil),       // 5: rentalmanagement.CancelRentalResponse
	(*ListAvailableCarsRequest)(nil),   // 6: rentalmanagement.ListAvailableCarsRequest
	(*ListAvailableCarsResponse)(nil),  // 7: rentalmanagement.ListAvailableCarsResponse
	(*RegisterCustomerRequest)(nil),    // 8: rentalmanagement.RegisterCustomerRequest
	(*RegisterCustomerResponse)(nil),   // 9: rentalmanagement.RegisterCustomerResponse
	(*DeregisterCustomerRequest)(nil),  // 10: rentalmanagement.DeregisterCustomerRequest
	(*DeregisterCustomerResponse)(nil), // 11: rentalmanagement.DeregisterCustomerResponse
	(*Customer)(nil),                   // 12: rentalmanagement.Customer
	(*Rental)(nil),                     // 13: rentalmanagement.Rental
	(*Car)(nil),                        // 14: rentalmanagement.Car
	(*Vin)(nil),                        // 15: rentalmanagement.Vin
	(*ErrorDetail)(nil),                // 16: rentalmanagement.ErrorDetail
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_src_api_specification_api_specification_am_rental_management_proto_depIdxs = []int32{
	17, // 0: rentalmanagement.RentCarRequest.startDate:type_name -> google.protobuf.Timestamp
	17, // 1: rentalmanagement.RentCarRequest.endDate:type_name -> google.protobuf.Timestamp
	15, // 2: rentalmanagement.RentCarRequest.vin:type_name -> rentalmanagement.Vin
	13, // 3: rentalmanagement.RentCarResponse.rental:type_name -> rentalmanagement.Rental
	16, // 4: rentalmanagement.RentCarResponse.error:type_name -> rentalmanagement.ErrorDetail
	13, // 5: rentalmanagement.ListRentalsResponse.rentals:type_name -> rentalmanagement.Rental
	16, // 6: rentalmanagement.ListRentalsResponse.error:type_name -> rentalmanagement.ErrorDetail
	16, // 7: rentalmanagement.CancelRentalResponse.error:type_name -> rentalmanagement.ErrorDetail
	17, // 8: rentalmanagement.ListAvailableCarsRequest.startDate:type_name -> google.protobuf.Timestamp
	17, // 9: rentalmanagement.ListAvailableCarsRequest.endDate:type_name -> google.protobuf.Timestamp
	14, // 10: rentalmanagement.ListAvailableCarsResponse.cars:type_name -> rentalmanagement.Car
	16, // 11: rentalmanagement.ListAvailableCarsResponse.error:type_name -> rentalmanagement.ErrorDetail
	12, // 12: rentalmanagement.RegisterCustomerResponse.customer:type_name -> rentalmanagement.Customer
	16, // 13: rentalmanagement.RegisterCustomerResponse.error:type_name -> rentalmanagement.ErrorDetail
	16, // 14: rentalmanagement.DeregisterCustomerResponse.error:type_name -> rentalmanagement.ErrorDetail
	17, // 15: rentalmanagement.Rental.startDate:type_name -> google.protobuf.Timestamp
	17, // 16: rentalmanagement.Rental.endDate:type_name -> google.protobuf.Timestamp
	15, // 17: rentalmanagement.Rental.vin:type_name -> rentalmanagement.Vin
	15, // 18: rentalmanagement.Car.vin:type_name -> rentalmanagement.Vin
	6,  // 19: rentalmanagement.RentalsCollectionService.ListAvailableCars:input_type -> rentalmanagement.ListAvailableCarsRequest
	0,  // 20: rentalmanagement.CustomerService.RentCar:input_type -> rentalmanagement.RentCarRequest
	2,  // 21: rentalmanagement.CustomerService.ListRentals:input_type -> rentalmanagement.ListRentalsRequest
	4,  // 22: rentalmanagement.CustomerService.CancelRental:input_type -> rentalmanagement.CancelRentalRequest
	8,  // 23: rentalmanagement.CustomersCollectionService.RegisterCustomer:input_type -> rentalmanagement.RegisterCustomerRequest
	10, // 24: rentalmanagement.CustomersCollectionService.DeregisterCustomer:input_type -> rentalmanagement.DeregisterCustomerRequest
	7,  // 25: rentalmanagement.RentalsCollectionService.ListAvailableCars:output_type -> rentalmanagement.ListAvailableCarsResponse
	1,  // 26: rentalmanagement.CustomerService.RentCar:output_type -> rentalmanagement.RentCarResponse
	3,  // 27: rentalmanagement.CustomerService.ListRentals:output_type -> rentalmanagement.ListRentalsResponse
	5,  // 28: rentalmanagement.CustomerService.CancelRental:output_type -> rentalmanagement.CancelRentalResponse
	9,  // 29: rentalmanagement.CustomersCollectionService.RegisterCustomer:output_type -> rentalmanagement.RegisterCustomerResponse
	11, // 30: rentalmanagement.CustomersCollectionService.DeregisterCustomer:output_type -> rentalmanagement.DeregisterCustomerResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_src_api_specification_api_specification_am_rental_management_proto_init() }
func file_src_api_specification_api_specification_am_rental_management_proto_init() {
	if File_src_api_specification_api_specification_am_rental_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentCarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRentalsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRentalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRentalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRentalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAvailableCarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAvailableCarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCustomerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeregisterCustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeregisterCustomerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rental); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_rental_management_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_api_specification_api_specification_am_rental_management_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_src_api_specification_api_specification_am_rental_management_proto_goTypes,
		DependencyIndexes: file_src_api_specification_api_specification_am_rental_management_proto_depIdxs,
		MessageInfos:      file_src_api_specification_api_specification_am_rental_management_proto_msgTypes,
	}.Build()
	File_src_api_specification_api_specification_am_rental_management_proto = out.File
	file_src_api_specification_api_specification_am_rental_management_proto_rawDesc = nil
	file_src_api_specification_api_specification_am_rental_management_proto_goTypes = nil
	file_src_api_specification_api_specification_am_rental_management_proto_depIdxs = nil
}
